### ISSUE TITLE
Ending tag not recognized

### ISSUE THREAD

**Issue by Betanu701** [Digitalbrainstem/ejs-grammar#35]
## Steps to reproduce:
`
  <% if(foo) { %>
        <hr />
        <h3>Test Area</h3>
        <p>
          <a class="btn-sm" href="/test/testpage">Test Page</a>
        </p>
        <% } %>
`
![image](https://user-images.githubusercontent.com/5798012/55809199-8051c880-5ab3-11e9-92e4-a1f99bb94971.png)

<table><td>
📝 <strong>Note:</strong> Remember to link to a repository or upload a code snippet that reproduces the issue as an attachment (or a code block if it’s short) to this issue: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
</td></table>

```ejs
<%# short code snippet that reproduces the issue goes here %>
```

## Expected result:
The ending tag should be blue.

**Comment by andyli** [comment]
Minimal example:
```
<% if (true) { %> abc <% } %>
```
![image](https://user-images.githubusercontent.com/103977/55936081-dcf5e480-5c67-11e9-8658-c5e15404c350.png)
The last `%>` is not highlighted correctly.

My ejs extension info:
```
Name: EJS language support
Id: digitalbrainstem.javascript-ejs-support
Description: 2018 - EJS language support for Visual Studio Code.
Version: 0.5.0
Publisher: DigitalBrainstem
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DigitalBrainstem.javascript-ejs-support
```

**Comment by ExE-Boss** [comment]
You can do:
```
<% if (true) { %> abc <% }
%>
```
Which fixes it.

---

The following is also broken:
```
<% if (true) { 'js code' } %>
```
This means that the cause is probably something in JavaScript.

**Comment by mattschuette** [comment]
But reformatting my code is not a fix for a code formatter. In fact,
```
<% if () { %>
<% } %>
```
or even just
```
<% if () {} %>
```
while not really valid, are sufficient to exhibit the problem, where 
```
<% for () { %>
<% } %>
```
and
```
<% while () { %>
<% } %>
```
(or those in one line) are pretty minimal snippets that don't break the formatting. I feel like this has something to do with how `if` blocks are handled.

**Comment by Betanu701** [comment]
Just published a new update. It is now "html" with javascript and ejs tags injected into it. All the above should be fixed.

**Comment by guilhermeoc97** [comment]
Still broken here. Latest version (1.1.0) and VSCode version 1.37.1

![Annotation 2019-08-23 185742](https://user-images.githubusercontent.com/22584437/63626168-59b2ab00-c5d8-11e9-988c-0a69cd6065a3.png)

**Comment by ExE-Boss** [comment]
Yeah, this change to injecting into HTML also broke:
```ejs
<%
// Inserts a link to an in-page section, given the section name.
//
// Parameters:
//  $0  Anchor name; you may use spaces here instead of underscores -- these
//      are converted for you.
//  $1  (optional) Text to display instead of the anchor name itself.
//
// Examples:
//  {{anch("Some section's title")}}
//  {{anch("Another section name", "the information elsewhere in this article.")}}

var text = $1 || $0;
var anchor = '#' + string.replace($0, " ", "_");

%><a href="<%- anchor %>"><%- text %></a>
```
highlighting is completely broken from `var anchor`:

[![Broken EJS syntax highlighting](https://user-images.githubusercontent.com/3889017/63626694-a318ef80-c604-11e9-862b-8262661bedc2.png)](https://github.com/mdn/kumascript/blob/master/macros/anch.ejs)

**Comment by Betanu701** [comment]
This is what I am seeing. I am not sure where the issue lies. 

![image](https://user-images.githubusercontent.com/5798012/63631491-47476a00-c5f6-11e9-9963-e4881e9a0677.png)

**Comment by Betanu701** [comment]
@guilhermeoc97 can you provided the entire file? To me it looks like something is broken above your snippet.

**Comment by guilhermeoc97** [comment]
Sure, here it is:

```
<%- include("header") %>
<div class="container-fluid">
    <div class="row text-center">
        <h1 class="col">NetSpeed</h1>
    </div>
    <div class="row text-center">
        <h2 class="col">Test history</h2>
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-sm">
            <thead class="thead-light text-center">
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Average download speed</th>
                    <th>Measured download speed</th>
                    <th>Average upload speed</th>
                    <th>Measured upload speed</th>
                </tr>
            </thead>
            <tbody class="text-center">
                <% rows.forEach(value => { %>
                    <tr>
                        <td><%= value.id %></td>
                        <td><%= moment(value.date).locale(locale).format("LLL") %></td>
                        <td><%= (value.avgDownload * 8).toFixed(2) %> Mbps</td>
                        <td><%= (value.download * 8).toFixed(2) %> Mbps</td>
                        <td><%= (value.avgUpload * 8).toFixed(2) %> Mbps</td>
                        <td><%= (value.upload * 8).toFixed(2) %> Mbps</td>
                    </tr>
                <% }); %>
            </tbody>
        </table>
        <a class="btn btn-primary" role="button" href="/history/all/<%= count %> %>">Início</a>
        <% if (hasMorePages) { %>
            <a class="btn btn-primary" role="button" href="/history/all/<%= count %>/<%= rows.reverse()[0].id %>">Próximo</a>
        <% } %>
    </div>
</div>
<%- include("footer") %>
```

**Comment by Betanu701** [comment]
Thanks!  I was able to get the first 2 taken care of. I am still working on the last one.

**Comment by rmgreenstreet** [comment]
Has this been fixed yet? I'm seeing pretty much the same thing: Closing ejs `%>` tag is not highlighted on the first line (ignore the tooltip for 'input'). I believe it may be causing the issue down in the `<script>` tag below as well, where the first line declaring the function name is not highlighted, since the editor believes the original ejs line was not terminated. I'm unclear on whether this is purely a cosmetic thing within the editor itself, or if it is in turn causing an issue where the code in the `<script>` tag seems to not be run on the page.
 
![extendedejsissue](https://user-images.githubusercontent.com/50469309/72169274-691e6f00-3394-11ea-8482-808af726c81b.PNG)

`<%- include("../partials/header.ejs") %>

        <h1>Edit Post</h1>
        <form action="/posts/<%= post._id %>?_method=put" method="post" enctype="multipart/form-data" id="postEditForm">
            <div class="form-group">
                <label for="post[title]">Title</label>
                <input type="text" name="post[title]" value="<%= post.title %>">
            </div>
            <div class="form-group">
                <label for="post[price]">Price</label>
                <input type="number" step=".01" name="post[price]" value="<%= post.price %>">
            </div>
            <div class="form-group">
                <label for="post[description">Description</label>
                <textarea name="post[description]" ><%= post.description %></textarea>
            </div>
            <div class="form-group">
                <label for="post[location">Location</label>
                <input type="text" name="post[location]" value="<%= post.location %>">
            </div>
            <% post.images.forEach(function(image,i){ %>
                <div class="editImage card" style="width:18rem;">
                    <img src="<%= image.url %>" width="100px" class="card-img-bottom">
                    <div class="card-body">
                        <label for="image<%= i %>">
                            Delete?
                        </label>
                        <input type="checkbox" class="imageToDelete" id="image<%= i %>" name="imageToDelete[]" value="<%= image.publicId %>"></div>
                </div>
            <% }); %>
            <div class="form-group">
                <label for="image">Images</label>
                <input type="file" name="image" multiple="multiple" accept="images/*" id="imagesToUpload">
            </div>
            <button type="submit">
                Submit
            </button>
        </form>

        <script>
            function checkUploads() {
                //find post edit form
                let postEditForm = document.getElementById('postEditForm');
                //add submit listener to postEditForm
                postEditForm.addEventListener('submit', (event) => {
                    //find number of images to upload
                    let imagesToUpload = document.getElementById('imagesToUpload').length;
                    //find number of existing images
                    let existingImages = document.querySelectorAll('.imageToDelete').length;
                    //ind total number of potential deletions
                    let imagesToDelete = document.querySelectorAll('.imageToDelete:checked').length;
                    let newTotal=existingImages-imageDeletions+imagesToUpload;
                    //figure out if the form can be submitted or not
                    if(newTotal > 4) {
                        event.preventDefault();
                        let removalAmt = newTotal -4;
                        alert(`A post can have a maximum of 4 images. Please remove at least ${removalAmt} image${removalAmt === 1 ? 's' : ''}!`);
                    }
                });
            }
        </script>

<%- include("../partials/footer.ejs") %>`

**Comment by ExE-Boss** [comment]
@rmgreenstreet That&nbsp;is&nbsp;only a&nbsp;display&nbsp;issue&nbsp;with the&nbsp;TextMate‑based&nbsp;grammar used&nbsp;by&nbsp;most&nbsp;editors and&nbsp;**GitHub**.

It&nbsp;has&nbsp;nothing to&nbsp;do with&nbsp;how **EJS**&nbsp;parses and&nbsp;processes the&nbsp;file.

**Comment by Betanu701** [comment]
@rmgreenstreet If you want, I have some updates in the [Revamp-ejs](https://github.com/Digitalbrainstem/ejs-grammar/tree/Revamp-ejs) Branch. Feel free to load this into your own environment and give it a test run. This is still a work in progress, but should fix many of your issues.

**Comment by rmgreenstreet** [comment]
Thanks! I appreciate the response, and after some rubber-ducking found my actual issue. Like you say, the only thing this affects is the display within the editor. No real issue on my end :)

**Comment by Betanu701** [comment]
This has been fixed in version 1.2
